name: flutter_games
description: "Flutter Games."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  mobx: ^2.1.4
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  material_symbols_icons: ^4.2762.0
  flutter_mobx: ^2.2.1+1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/